
<h2>Current participants (<span id="participant-count"></span>)</h2>

<div class="hidden" id="event_id"><?php echo $this->escape($this->eventId) ?></div>

<div id="winner">
    <div style="text-align: center;"><h2>And the winner is...</h2></div>
    <p><span id="winner-message"></span>
        <img id="winner-profilePic" src="" alt="" width="64" height="64" style="vertical-align: middle; margin-left: 25px;"/></p>
    <div class="hidden" id="winner-id"></div>
    <div class="winner-not-here"><button id="winner-notHere">Not here!</button></div>
</div>

<div id="participants">
    <ul class="list" id="participant-list">
    </ul>
    <div class="clear">&nbsp;</div>
</div><!-- end participants -->
<?php $this->inlineScript()->appendScript(<<<EOL

function renderList(eventId) {
    var parent = $('#participants');
    var list = $('#participant-list').detach();
    list.empty();
    $.getJSON('/index/list/?event=' + eventId, function (data) {
        $('#participant-count').text(data.length);
        $.each(data, function (index, value) {
            list.append(
                '<li class="element" id="' + value.member_id + '">'
                + '<a href="http://www.meetup.com/phpbenelux/members/' + value.member_id + '" title="' + value.name + '" rel="nofollow">'
                + '<img src="' + value.thumb_link + '" width="115" height="115" alt="' + value.name + '"/>'
                + '</li>');
        });
    });
    parent.append(list);
}


function randomizer()
{
    var winner = Math.floor((Math.random() * 6));
    $.each($('#participant-list').children(), function (index, value) {
        if (index != winner) {
            $(value).css('border-color', 'red');
        } else {
            $(value).css('border-color', 'green');
            $('#winner-message').text($(value).children().attr('title'));
            $('#winner-profilePic').attr('src', $(value).children().children().attr('src'));
            $('#winner-id').text($(value).attr('id'));
        }
    });
}

function pickWinner(total) {
    var count = 0;
    var int = self.setInterval(function() {
        randomizer();
        console.log('Running contestant #' + count);
        if (count == total) {
            self.clearInterval(int);
            $('#winner').show();
            var eventId = $('#event_id').text();
            var memberId = $('#winner-id').text();
            storeWinner(eventId, memberId, 0);
            renderList(eventId);
        }
        count++;
    }, 1500);
}

function storeWinner(eventId, memberId, notHere) {
    $.post('/index/update', {
        eventId: eventId,
        memberId: memberId,
        winner: 1,
        notHere: notHere
    });
}

$(document).ready(function() {
    $('#winner').hide();
    var eventId = $('#event_id').text();
    renderList(eventId);
    $('#hacking').click(function() {
        pickWinner(3);
    });
    $('#winner-notHere').click(function() {
        var eventId = $('#event_id').text();
        var memberId = $('#winner-id').text();
        storeWinner(eventId, memberId, 1);
        $('#winner').hide();
        pickWinner(3);
    });
});

EOL
) ?>